[package]
name = "kin"
version = "0.1.0"
authors = ["Philip Crockett <contact@philcrockett.com>"]
edition = "2018"

[dependencies]
sodiumoxide = "0.2.0"
structopt = "0.2.10"
quicli = "0.4.0"
failure = "0.1.3"
log = "0.4.6"
