[package]
name = "kin"
version = "0.1.0"
authors = ["Philip Crockett <contact@philcrockett.com>"]
edition = "2018"

[dependencies]
kin_core = { path = "../kin_core" }
serde = { version = "1.0.82", features = ["derive"] }
